package com.gamevault.common

fun getStrings(lang: String): AppStrings = when {
    lang.startsWith("English")  -> AppStrings.EN
    lang.startsWith("Español")  -> AppStrings.ES
    lang.startsWith("Deutsch")  -> AppStrings.DE
    lang.startsWith("Français") -> AppStrings.FR
    lang.startsWith("中文")      -> AppStrings.ZH
    else                         -> AppStrings.RU
}

data class AppStrings(
    // GameList
    val loading: String, val noFavs: String, val tapHeart: String,
    val noResults: String, val search: String, val all: String,
    val favourites: String, val allGames: String, val gameVault: String,
    val discover: String, val games: String, val sortTitle: String,
    val apply: String, val settings: String, val about: String,
    val home: String, val compact: String,
    val sortRatingDesc: String, val sortRatingAsc: String, val sortName: String,
    val sortRelease: String, val sortMetacritic: String, val sortPlaytime: String,
    val sortSteam: String, val sortEpic: String, val sortPS: String, val sortXbox: String,
    val platformAll: String, val platformMobile: String,
    val sortGeneral: String, val sortByStore: String,
    val gameLibrary: String,
    // Settings
    val settingsTitle: String, val langTitle: String, val langInterface: String,
    val displayTitle: String, val compactCards: String, val compactCardsSub: String,
    val showRating: String, val showRatingSub: String,
    val showMeta: String, val showMetaSub: String,
    val contentTitle: String, val adultFilter: String, val adultFilterSub: String,
    val appTitle: String, val notifications: String, val notificationsSub: String,
    val autoRefresh: String, val autoRefreshSub: String,
    val caching: String, val cachingSub: String,
    val dataTitle: String, val dataSource: String, val database: String,
    val clearCache: String, val clearCacheDone: String, val clearCacheSub: String,
    val aboutTitle: String, val version: String, val tech: String,
    val applyChanges: String, val unsavedChanges: String,
    val logout: String, val logoutTitle: String, val logoutConfirm: String,
    val clearCacheTitle: String, val clearCacheConfirm: String,
    val cancel: String, val confirm: String, val online: String,
    val chooseLanguage: String,
    // Auth
    val authSubtitle: String, val login: String, val register: String,
    val username: String, val email: String, val password: String,
    val loginBtn: String, val registerBtn: String, val forgotPassword: String,
    val loginAsGuest: String, val enterEmail: String, val passwordShort: String,
    val enterUsername: String,
    // Discover
    val discoverTitle: String, val discoverSub: String,
    val discoverLoading: String, val noConnection: String, val retry: String,
    val newGames: String,
    // GameDetail
    val rating: String, val metacritic: String, val playtime: String,
    val released: String, val aboutGame: String, val platforms: String,
    val developers: String, val publishers: String, val na: String, val tba: String,
) {
    companion object {
        val RU = AppStrings(
            loading="Загрузка игр...", noFavs="Нет избранных игр", tapHeart="Нажми ♡ на любой игре",
            noResults="Ничего не найдено", search="Поиск игр...", all="Все",
            favourites="⭐ Избранное", allGames="🎮 Все игры", gameVault="🎮 GameVault",
            discover="🔍 Обзор", games="игр", sortTitle="Сортировка", apply="Применить",
            settings="Настройки", about="О приложении", home="Главная", compact="Компактный вид",
            sortRatingDesc="По рейтингу ↓", sortRatingAsc="По рейтингу ↑",
            sortName="По названию А–Я", sortRelease="По дате выхода",
            sortMetacritic="По Metacritic", sortPlaytime="По времени игры",
            sortSteam="🖥 Популярно в Steam", sortEpic="⚡ Популярно в Epic",
            sortPS="🎮 Топ на PlayStation", sortXbox="🟢 Топ на Xbox",
            platformAll="Все", platformMobile="Мобильные",
            sortGeneral="📊 Общая", sortByStore="🛒 По магазину",
            gameLibrary="Игровая библиотека",
            settingsTitle="Настройки", langTitle="Язык", langInterface="Язык интерфейса",
            displayTitle="Отображение", compactCards="Компактные карточки",
            compactCardsSub="Небольшие карточки, больше игр на экране",
            showRating="Показывать рейтинг", showRatingSub="Звёздочка рейтинга на карточке",
            showMeta="Показывать Metacritic", showMetaSub="Оценка критиков на карточке",
            contentTitle="Контент", adultFilter="Фильтр 18+", adultFilterSub="Скрывать игры для взрослых",
            appTitle="Приложение", notifications="Уведомления", notificationsSub="Новые игры и обновления",
            autoRefresh="Авто-обновление", autoRefreshSub="Обновлять список при запуске",
            caching="Кеширование", cachingSub="Сохранять игры оффлайн",
            dataTitle="Данные", dataSource="Источник данных", database="База данных",
            clearCache="Очистить кеш", clearCacheDone="Кеш очищен ✓",
            clearCacheSub="Удалить загруженные данные",
            aboutTitle="О приложении", version="Версия", tech="Технологии",
            applyChanges="Применить изменения",
            unsavedChanges="Есть несохранённые изменения — нажмите «Применить»",
            logout="Выйти из аккаунта", logoutTitle="Выйти из аккаунта?",
            logoutConfirm="Вы уверены? Избранное сохранится.",
            clearCacheTitle="Очистить кеш?", clearCacheConfirm="Игры перезагрузятся при следующем запуске.",
            cancel="Отмена", confirm="Очистить", online="онлайн",
            chooseLanguage="Выберите язык",
            authSubtitle="Ваша игровая библиотека", login="Войти", register="Регистрация",
            username="Имя пользователя", email="Email", password="Пароль",
            loginBtn="Войти", registerBtn="Создать аккаунт", forgotPassword="Забыли пароль?",
            loginAsGuest="Войти как гость", enterEmail="Введите email",
            passwordShort="Пароль слишком короткий", enterUsername="Введите имя пользователя",
            discoverTitle="Обзор", discoverSub="Популярное · Новинки · Магазины",
            discoverLoading="Загрузка контента...", noConnection="Нет подключения", retry="Повторить",
            newGames="игр",
            rating="Рейтинг", metacritic="Metacritic", playtime="Время игры",
            released="Год выхода", aboutGame="Об игре", platforms="Платформы",
            developers="Разработчики", publishers="Издатели", na="Н/Д", tba="Скоро",
        )
        val EN = AppStrings(
            loading="Loading games...", noFavs="No favourites yet", tapHeart="Tap ♡ on any game",
            noResults="Nothing found", search="Search games...", all="All",
            favourites="⭐ Favourites", allGames="🎮 All Games", gameVault="🎮 GameVault",
            discover="🔍 Discover", games="games", sortTitle="Sort", apply="Apply",
            settings="Settings", about="About", home="Home", compact="Compact view",
            sortRatingDesc="Rating ↓", sortRatingAsc="Rating ↑",
            sortName="Name A–Z", sortRelease="Release date",
            sortMetacritic="Metacritic", sortPlaytime="By playtime",
            sortSteam="🖥 Popular on Steam", sortEpic="⚡ Popular on Epic",
            sortPS="🎮 Top on PlayStation", sortXbox="🟢 Top on Xbox",
            platformAll="All", platformMobile="Mobile",
            sortGeneral="📊 General", sortByStore="🛒 By store",
            gameLibrary="Game library",
            settingsTitle="Settings", langTitle="Language", langInterface="Interface language",
            displayTitle="Display", compactCards="Compact cards",
            compactCardsSub="Smaller cards, more games on screen",
            showRating="Show rating", showRatingSub="Star rating on card",
            showMeta="Show Metacritic", showMetaSub="Critic score on card",
            contentTitle="Content", adultFilter="Adult filter", adultFilterSub="Hide adult games",
            appTitle="Application", notifications="Notifications", notificationsSub="New games and updates",
            autoRefresh="Auto-refresh", autoRefreshSub="Refresh list on startup",
            caching="Caching", cachingSub="Save games offline",
            dataTitle="Data", dataSource="Data source", database="Database",
            clearCache="Clear cache", clearCacheDone="Cache cleared ✓",
            clearCacheSub="Delete downloaded data",
            aboutTitle="About", version="Version", tech="Technologies",
            applyChanges="Apply changes",
            unsavedChanges="Unsaved changes — tap Apply",
            logout="Log out", logoutTitle="Log out?",
            logoutConfirm="Are you sure? Favourites will be saved.",
            clearCacheTitle="Clear cache?", clearCacheConfirm="Games will reload on next launch.",
            cancel="Cancel", confirm="Clear", online="online",
            chooseLanguage="Choose language",
            authSubtitle="Your game library", login="Log in", register="Register",
            username="Username", email="Email", password="Password",
            loginBtn="Log in", registerBtn="Create account", forgotPassword="Forgot password?",
            loginAsGuest="Continue as guest", enterEmail="Enter email",
            passwordShort="Password too short", enterUsername="Enter username",
            discoverTitle="Discover", discoverSub="Popular · New · Stores",
            discoverLoading="Loading content...", noConnection="No connection", retry="Retry",
            newGames="games",
            rating="Rating", metacritic="Metacritic", playtime="Playtime",
            released="Released", aboutGame="About", platforms="Platforms",
            developers="Developers", publishers="Publishers", na="N/A", tba="TBA",
        )
        val ES = AppStrings(
            loading="Cargando juegos...", noFavs="Sin favoritos", tapHeart="Toca ♡ en un juego",
            noResults="Sin resultados", search="Buscar juegos...", all="Todos",
            favourites="⭐ Favoritos", allGames="🎮 Todos los juegos", gameVault="🎮 GameVault",
            discover="🔍 Descubrir", games="juegos", sortTitle="Ordenar", apply="Aplicar",
            settings="Ajustes", about="Acerca de", home="Inicio", compact="Vista compacta",
            sortRatingDesc="Valoración ↓", sortRatingAsc="Valoración ↑",
            sortName="Nombre A–Z", sortRelease="Fecha lanzamiento",
            sortMetacritic="Metacritic", sortPlaytime="Tiempo de juego",
            sortSteam="🖥 Popular en Steam", sortEpic="⚡ Popular en Epic",
            sortPS="🎮 Top PlayStation", sortXbox="🟢 Top Xbox",
            platformAll="Todos", platformMobile="Móvil",
            sortGeneral="📊 General", sortByStore="🛒 Por tienda",
            gameLibrary="Biblioteca de juegos",
            settingsTitle="Ajustes", langTitle="Idioma", langInterface="Idioma de interfaz",
            displayTitle="Pantalla", compactCards="Tarjetas compactas",
            compactCardsSub="Tarjetas pequeñas, más juegos en pantalla",
            showRating="Mostrar valoración", showRatingSub="Estrella de valoración en tarjeta",
            showMeta="Mostrar Metacritic", showMetaSub="Puntuación en tarjeta",
            contentTitle="Contenido", adultFilter="Filtro +18", adultFilterSub="Ocultar juegos adultos",
            appTitle="Aplicación", notifications="Notificaciones", notificationsSub="Nuevos juegos y actualizaciones",
            autoRefresh="Auto-actualización", autoRefreshSub="Actualizar al iniciar",
            caching="Caché", cachingSub="Guardar juegos sin conexión",
            dataTitle="Datos", dataSource="Fuente de datos", database="Base de datos",
            clearCache="Limpiar caché", clearCacheDone="Caché limpiada ✓",
            clearCacheSub="Eliminar datos descargados",
            aboutTitle="Acerca de", version="Versión", tech="Tecnologías",
            applyChanges="Aplicar cambios",
            unsavedChanges="Cambios sin guardar — toca Aplicar",
            logout="Cerrar sesión", logoutTitle="¿Cerrar sesión?",
            logoutConfirm="¿Estás seguro? Los favoritos se guardarán.",
            clearCacheTitle="¿Limpiar caché?", clearCacheConfirm="Los juegos se recargarán al iniciar.",
            cancel="Cancelar", confirm="Limpiar", online="en línea",
            chooseLanguage="Elegir idioma",
            authSubtitle="Tu biblioteca de juegos", login="Entrar", register="Registrarse",
            username="Nombre de usuario", email="Correo", password="Contraseña",
            loginBtn="Entrar", registerBtn="Crear cuenta", forgotPassword="¿Olvidaste tu contraseña?",
            loginAsGuest="Entrar como invitado", enterEmail="Introduce el correo",
            passwordShort="Contraseña muy corta", enterUsername="Introduce el nombre de usuario",
            discoverTitle="Descubrir", discoverSub="Popular · Novedades · Tiendas",
            discoverLoading="Cargando contenido...", noConnection="Sin conexión", retry="Reintentar",
            newGames="juegos",
            rating="Valoración", metacritic="Metacritic", playtime="Tiempo de juego",
            released="Lanzamiento", aboutGame="Acerca de", platforms="Plataformas",
            developers="Desarrolladores", publishers="Editores", na="N/D", tba="Próximamente",
        )
        val DE = AppStrings(
            loading="Spiele laden...", noFavs="Keine Favoriten", tapHeart="Tippe ♡ bei einem Spiel",
            noResults="Keine Ergebnisse", search="Spiele suchen...", all="Alle",
            favourites="⭐ Favoriten", allGames="🎮 Alle Spiele", gameVault="🎮 GameVault",
            discover="🔍 Entdecken", games="Spiele", sortTitle="Sortieren", apply="Übernehmen",
            settings="Einstellungen", about="Über uns", home="Startseite", compact="Kompakt",
            sortRatingDesc="Bewertung ↓", sortRatingAsc="Bewertung ↑",
            sortName="Name A–Z", sortRelease="Erscheinungsdatum",
            sortMetacritic="Metacritic", sortPlaytime="Spielzeit",
            sortSteam="🖥 Beliebt auf Steam", sortEpic="⚡ Beliebt auf Epic",
            sortPS="🎮 Top PlayStation", sortXbox="🟢 Top Xbox",
            platformAll="Alle", platformMobile="Mobil",
            sortGeneral="📊 Allgemein", sortByStore="🛒 Nach Shop",
            gameLibrary="Spielebibliothek",
            settingsTitle="Einstellungen", langTitle="Sprache", langInterface="Oberflächensprache",
            displayTitle="Anzeige", compactCards="Kompakte Karten",
            compactCardsSub="Kleinere Karten, mehr Spiele auf dem Bildschirm",
            showRating="Bewertung anzeigen", showRatingSub="Sternbewertung auf Karte",
            showMeta="Metacritic anzeigen", showMetaSub="Kritikerbewertung auf Karte",
            contentTitle="Inhalte", adultFilter="Altersfilter 18+", adultFilterSub="Erwachsenenspiele ausblenden",
            appTitle="Anwendung", notifications="Benachrichtigungen", notificationsSub="Neue Spiele und Updates",
            autoRefresh="Auto-Aktualisierung", autoRefreshSub="Liste beim Start aktualisieren",
            caching="Caching", cachingSub="Spiele offline speichern",
            dataTitle="Daten", dataSource="Datenquelle", database="Datenbank",
            clearCache="Cache leeren", clearCacheDone="Cache geleert ✓",
            clearCacheSub="Heruntergeladene Daten löschen",
            aboutTitle="Über uns", version="Version", tech="Technologien",
            applyChanges="Änderungen übernehmen",
            unsavedChanges="Ungespeicherte Änderungen — Übernehmen tippen",
            logout="Abmelden", logoutTitle="Abmelden?",
            logoutConfirm="Sind Sie sicher? Favoriten bleiben gespeichert.",
            clearCacheTitle="Cache leeren?", clearCacheConfirm="Spiele werden beim nächsten Start neu geladen.",
            cancel="Abbrechen", confirm="Leeren", online="online",
            chooseLanguage="Sprache wählen",
            authSubtitle="Ihre Spielebibliothek", login="Anmelden", register="Registrieren",
            username="Benutzername", email="E-Mail", password="Passwort",
            loginBtn="Anmelden", registerBtn="Konto erstellen", forgotPassword="Passwort vergessen?",
            loginAsGuest="Als Gast fortfahren", enterEmail="E-Mail eingeben",
            passwordShort="Passwort zu kurz", enterUsername="Benutzername eingeben",
            discoverTitle="Entdecken", discoverSub="Beliebt · Neu · Shops",
            discoverLoading="Inhalte laden...", noConnection="Keine Verbindung", retry="Wiederholen",
            newGames="Spiele",
            rating="Bewertung", metacritic="Metacritic", playtime="Spielzeit",
            released="Erschienen", aboutGame="Über das Spiel", platforms="Plattformen",
            developers="Entwickler", publishers="Verleger", na="N/V", tba="Demnächst",
        )
        val FR = AppStrings(
            loading="Chargement...", noFavs="Pas de favoris", tapHeart="Appuie sur ♡",
            noResults="Aucun résultat", search="Chercher des jeux...", all="Tous",
            favourites="⭐ Favoris", allGames="🎮 Tous les jeux", gameVault="🎮 GameVault",
            discover="🔍 Découvrir", games="jeux", sortTitle="Trier", apply="Appliquer",
            settings="Paramètres", about="À propos", home="Accueil", compact="Vue compacte",
            sortRatingDesc="Note ↓", sortRatingAsc="Note ↑",
            sortName="Nom A–Z", sortRelease="Date de sortie",
            sortMetacritic="Metacritic", sortPlaytime="Temps de jeu",
            sortSteam="🖥 Populaire Steam", sortEpic="⚡ Populaire Epic",
            sortPS="🎮 Top PlayStation", sortXbox="🟢 Top Xbox",
            platformAll="Tous", platformMobile="Mobile",
            sortGeneral="📊 Général", sortByStore="🛒 Par boutique",
            gameLibrary="Bibliothèque de jeux",
            settingsTitle="Paramètres", langTitle="Langue", langInterface="Langue de l'interface",
            displayTitle="Affichage", compactCards="Cartes compactes",
            compactCardsSub="Petites cartes, plus de jeux à l'écran",
            showRating="Afficher la note", showRatingSub="Étoile de note sur la carte",
            showMeta="Afficher Metacritic", showMetaSub="Score des critiques sur la carte",
            contentTitle="Contenu", adultFilter="Filtre 18+", adultFilterSub="Masquer les jeux adultes",
            appTitle="Application", notifications="Notifications", notificationsSub="Nouveaux jeux et mises à jour",
            autoRefresh="Actualisation auto", autoRefreshSub="Actualiser au démarrage",
            caching="Mise en cache", cachingSub="Sauvegarder les jeux hors ligne",
            dataTitle="Données", dataSource="Source de données", database="Base de données",
            clearCache="Vider le cache", clearCacheDone="Cache vidé ✓",
            clearCacheSub="Supprimer les données téléchargées",
            aboutTitle="À propos", version="Version", tech="Technologies",
            applyChanges="Appliquer les modifications",
            unsavedChanges="Modifications non sauvegardées — appuie sur Appliquer",
            logout="Se déconnecter", logoutTitle="Se déconnecter ?",
            logoutConfirm="Tu es sûr ? Les favoris seront sauvegardés.",
            clearCacheTitle="Vider le cache ?", clearCacheConfirm="Les jeux seront rechargés au prochain lancement.",
            cancel="Annuler", confirm="Vider", online="en ligne",
            chooseLanguage="Choisir la langue",
            authSubtitle="Ta bibliothèque de jeux", login="Se connecter", register="S'inscrire",
            username="Nom d'utilisateur", email="E-mail", password="Mot de passe",
            loginBtn="Se connecter", registerBtn="Créer un compte", forgotPassword="Mot de passe oublié ?",
            loginAsGuest="Continuer en tant qu'invité", enterEmail="Entre ton e-mail",
            passwordShort="Mot de passe trop court", enterUsername="Entre ton nom d'utilisateur",
            discoverTitle="Découvrir", discoverSub="Populaire · Nouveautés · Boutiques",
            discoverLoading="Chargement du contenu...", noConnection="Pas de connexion", retry="Réessayer",
            newGames="jeux",
            rating="Note", metacritic="Metacritic", playtime="Temps de jeu",
            released="Sortie", aboutGame="À propos", platforms="Plateformes",
            developers="Développeurs", publishers="Éditeurs", na="N/D", tba="Bientôt",
        )
        val ZH = AppStrings(
            loading="加载中...", noFavs="无收藏", tapHeart="点击♡收藏",
            noResults="无结果", search="搜索游戏...", all="全部",
            favourites="⭐ 收藏", allGames="🎮 所有游戏", gameVault="🎮 GameVault",
            discover="🔍 发现", games="游戏", sortTitle="排序", apply="应用",
            settings="设置", about="关于", home="首页", compact="紧凑视图",
            sortRatingDesc="评分↓", sortRatingAsc="评分↑",
            sortName="名称A-Z", sortRelease="发行日期",
            sortMetacritic="Metacritic", sortPlaytime="游戏时间",
            sortSteam="🖥 Steam热门", sortEpic="⚡ Epic热门",
            sortPS="🎮 PlayStation热门", sortXbox="🟢 Xbox热门",
            platformAll="全部", platformMobile="手机",
            sortGeneral="📊 综合", sortByStore="🛒 按商店",
            gameLibrary="游戏库",
            settingsTitle="设置", langTitle="语言", langInterface="界面语言",
            displayTitle="显示", compactCards="紧凑卡片",
            compactCardsSub="小卡片，屏幕显示更多游戏",
            showRating="显示评分", showRatingSub="卡片上显示星级评分",
            showMeta="显示Metacritic", showMetaSub="卡片上显示评论家评分",
            contentTitle="内容", adultFilter="成人过滤器", adultFilterSub="隐藏成人游戏",
            appTitle="应用", notifications="通知", notificationsSub="新游戏和更新",
            autoRefresh="自动刷新", autoRefreshSub="启动时刷新列表",
            caching="缓存", cachingSub="离线保存游戏",
            dataTitle="数据", dataSource="数据来源", database="数据库",
            clearCache="清除缓存", clearCacheDone="缓存已清除 ✓",
            clearCacheSub="删除已下载数据",
            aboutTitle="关于", version="版本", tech="技术",
            applyChanges="应用更改",
            unsavedChanges="有未保存的更改 — 点击应用",
            logout="退出登录", logoutTitle="退出登录？",
            logoutConfirm="您确定吗？收藏将被保留。",
            clearCacheTitle="清除缓存？", clearCacheConfirm="下次启动时将重新加载游戏。",
            cancel="取消", confirm="清除", online="在线",
            chooseLanguage="选择语言",
            authSubtitle="您的游戏库", login="登录", register="注册",
            username="用户名", email="邮箱", password="密码",
            loginBtn="登录", registerBtn="创建账户", forgotPassword="忘记密码？",
            loginAsGuest="以访客身份继续", enterEmail="请输入邮箱",
            passwordShort="密码太短", enterUsername="请输入用户名",
            discoverTitle="发现", discoverSub="热门 · 新游戏 · 商店",
            discoverLoading="加载内容...", noConnection="无连接", retry="重试",
            newGames="游戏",
            rating="评分", metacritic="Metacritic", playtime="游戏时间",
            released="发行年份", aboutGame="关于游戏", platforms="平台",
            developers="开发商", publishers="发行商", na="N/A", tba="即将推出",
        )
    }
}
